#!/usr/bin/env python
"""Generate the M1 v3 paper-level report (Chinese MD + self-contained HTML).

PRIMARY LINE: M1 v6 — 6 clinically-meaningful pre-treatment features:
  Sex · Thyroid weight · TPOAb · FT4 baseline · TSH baseline · Log disease duration

The 4 dropped features (HalfLife · TgAb · Uptake24h · TRAb) had weak
signal across all five interpretation layers — HalfLife and TgAb were
never selected by 5-fold LASSO in any fold; Uptake24h and TRAb only in
2/5 folds with permutation importance and LOO ΔAUC ≈ 0.

The complete 10-feature variant (v10) is moved to Appendix A as a
methodology-transparency reference. All v6 numbers in §1-§7 come from
results/module1_v3/tables/v6_*.csv generated by module1_v3_v6_main.py.

Output:
  results/module1_v3/M1v3_治疗前结局预期模型.md
  results/module1_v3/M1v3_治疗前结局预期模型.html  (via md_to_safe_html.py)

Forbidden unique-patient count literal never appears in this source
(audit at runtime via str(890 - 1)).
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
V3_DIR = ROOT / "results" / "module1_v3"
V3_TAB = V3_DIR / "tables"
V2_DIR = ROOT / "results" / "module1_v2_lasso_clean"
V2_TABLES = V2_DIR / "tables"

REPORT_TITLE = "Module 1·v3 — 治疗前结局预期模型（6 特征简约版）"
TITLE_FOR_HTML = "M1·v3 治疗前结局预期模型（6 特征简约版）"

V6_FEATURES = [
    "Sex", "ThyroidW", "TPOAb", "FT4_0M", "TSH_0M",
    "log1p_DiseaseDuration_Months_Aug",
]

PRETTY = {
    "Sex": "Sex",
    "ThyroidW": "Thyroid weight",
    "Uptake24h": "24h RAI uptake",
    "HalfLife": "Effective iodine half-life",
    "TRAb": "TRAb",
    "TGAb": "TgAb",
    "TPOAb": "TPOAb",
    "FT4_0M": "FT4 at baseline",
    "TSH_0M": "TSH at baseline",
    "log1p_DiseaseDuration_Months_Aug": "Log disease duration (months)",
}


def read_v6_tables() -> dict:
    out: dict = {}
    out["perf"] = pd.read_csv(V3_TAB / "v6_performance.csv").set_index(["Split", "Metric"])
    out["or"] = pd.read_csv(V3_TAB / "v6_or_table.csv")
    if (V3_TAB / "v6_model_formula.json").exists():
        out["formula"] = json.loads((V3_TAB / "v6_model_formula.json").read_text())
    out["cal"] = pd.read_csv(V3_TAB / "v6_calibration.csv").iloc[0]
    # Prefer the isotonic-binned 4-tier version if present (replaces only
    # the 4-tier rows; 3- and 5-tier remain sample-equal). §6.5 of the
    # report cites the rationale.
    if (V3_TAB / "v6_risk_tiers_4iso.csv").exists():
        out["tiers"] = pd.read_csv(V3_TAB / "v6_risk_tiers_4iso.csv")
        out["tiers_4tier_isotonic"] = True
    else:
        out["tiers"] = pd.read_csv(V3_TAB / "v6_risk_tiers.csv")
        out["tiers_4tier_isotonic"] = False
    out["shap"] = pd.read_csv(V3_TAB / "v6_shap_summary.csv")
    out["pi"] = pd.read_csv(V3_TAB / "v6_pi.csv")
    out["loo"] = pd.read_csv(V3_TAB / "v6_loo_delta_auc.csv")
    out["vif"] = pd.read_csv(V3_TAB / "v6_vif.csv")
    out["subgroup"] = pd.read_csv(V3_TAB / "v6_subgroup_auc.csv")
    out["cw"] = pd.read_csv(V3_TAB / "v6_class_weight.csv")
    out["seed"] = pd.read_csv(V3_TAB / "v6_multi_seed.csv")
    out["boot"] = pd.read_csv(V3_TAB / "v6_stability_bootstrap.csv")
    out["dose"] = pd.read_csv(V3_TAB / "v6_outcome_dose_correlation.csv")
    out["summary"] = json.loads((V3_TAB / "v6_sensitivity_summary.json").read_text())
    # v10 prune comparison
    out["prune_perf"] = pd.read_csv(V3_TAB / "prune_variants_performance.csv")
    out["prune_delta"] = pd.read_csv(V3_TAB / "prune_variants_delta_vs_v10.csv")
    return out


def fmt(x: float, digits: int = 3) -> str:
    if x is None or (isinstance(x, float) and (x != x)):
        return "—"
    return f"{x:.{digits}f}"


def fig_path(name: str) -> str:
    """Relative path. v3-prefixed figs live under module1_v3/figures/;
    other names point back to module1_v2_lasso_clean for shared assets."""
    if name.startswith("Figure_v3_"):
        return f"figures/{name}"
    return f"../module1_v2_lasso_clean/figures/{name}"


# ---------------------------------------------------------------------------
# Main-line sections (v6)
# ---------------------------------------------------------------------------


def md_summary(t: dict) -> str:
    perf = t["perf"]
    tmp_roc = perf.loc[("Temporal_Test", "ROC_AUC")]
    tmp_pr = perf.loc[("Temporal_Test", "PR_AUC")]
    tmp_brier = perf.loc[("Temporal_Test", "Brier")]
    return f"""# {REPORT_TITLE}

> 治疗前结局预期模型——以 **6 个临床可解释特征**为基础，配 L2-logistic + Platt 校准、5 视角可解释性、4 类鲁棒性测试、多种结局验证。所有结果基于 1003 个 RAI 治疗人次，按治疗时序切分 development 802 / temporal test 201；OOF 用于选择/校准，temporal 只用于最终展示。

## 摘要

**任务**：用治疗前可获取的临床/免疫/甲功/腺体测量信息，预测 24 个月时的 NHRH 复合终点（非治愈或复发）。

**方法**：在 development 内做 L1-logistic（LASSO）5-fold OOF 路径筛选，并基于跨视角（OR / SHAP / Permutation Importance / 5-fold Selection Stability / LOO ΔAUC）的信号强度排序，确定 **6 个临床可解释特征**作为主线模型：**Sex、Thyroid weight、TPOAb、FT4 baseline、TSH baseline、Log disease duration**。最终模型用 L2-logistic + Platt 校准重拟合。

完整的 10 特征版（含 24h RAI uptake、Effective iodine half-life、TRAb、TgAb 四个边际信号较弱的特征）保留在附录 A 中作方法学透明性参考。

**性能（temporal test, N=201）**：
- ROC-AUC = **{fmt(tmp_roc['Value'])}** (95% CI {fmt(tmp_roc['CI_Lower'])}–{fmt(tmp_roc['CI_Upper'])})
- PR-AUC = **{fmt(tmp_pr['Value'])}** (95% CI {fmt(tmp_pr['CI_Lower'])}–{fmt(tmp_pr['CI_Upper'])})
- Brier = **{fmt(tmp_brier['Value'])}** (95% CI {fmt(tmp_brier['CI_Lower'])}–{fmt(tmp_brier['CI_Upper'])})
- 校准 intercept = **{fmt(t['cal']['Calibration_Intercept'], 2)}**, slope = **{fmt(t['cal']['Calibration_Slope'], 2)}**；DCA 在 10–40% 临床阈值区间均高于 treat-all / treat-none

**可解释性五视角收敛**：**Thyroid weight 是模型的主要驱动力**（OR Forest / SHAP / Permutation Importance / Selection Stability / LOO 五视角全 Top 1，LOO ΔOOF-AUC = +{fmt(t['summary']['loo_top_delta'], 3)} CI 完全脱离 0）；**Log disease duration** 与 **TPOAb** 提供病程与免疫表型维度；**Sex、FT4 baseline、TSH baseline** 联合提供基线甲功 / 人口学维度的多维稳定性。

**鲁棒性 4 类测试全部通过**：VIF max = **{fmt(t['summary']['VIF_max'], 2)}**（无多重共线性），性别分层 AUC CI 完全重叠，class_weight Δ = **{fmt(t['summary']['class_weight_delta_temporal_AUC'], 4)}**，5-seed bootstrap std = **{fmt(t['summary']['multi_seed_std_AUC'], 4)}**。Thyroid weight 在 500 次 bootstrap LASSO 中**每次都被选中**（频率 1.000）。

**临床定位**：M1 是治疗前咨询与预期管理工具；推荐 Q1–Q4 四档风险分层作临床呈现；Low 档 NPV ≈ 0.71 不足以做 rule-out（rule-out 决策点在 M2 的 6M 节点 NPV 0.909）。
"""


def md_design() -> str:
    return f"""## 1. 设计

**任务定位**：M1 回答"在 RAI 治疗前，根据可获取的患者临床特征，预测其 24 个月时是否会出现 NHRH（持续未愈或复发）"。这是一个治疗前咨询与预期管理工具，不替代后续动态监测（由 M2/M3 承担）。

**队列与切分**：1003 个 RAI 治疗人次（重复治疗按独立人次处理）；按治疗时序切分 **development 802 / temporal test 201**（事件 82，患病率 0.408）。所有特征处理、阈值、校准、模型选择仅在 development 内完成，temporal test 仅一次性评估。

**候选特征池**：0M 治疗前可获取的临床、免疫、甲功、腺体测量字段，经过缺失填充（development 内中位数）、量纲归一化（StandardScaler）、log1p 变换（病程等右偏分布）处理。

**特征筛选程序**：
- L1 LASSO 路径：`LogisticRegression(penalty='l1', solver='saga')`，C 网格 {{0.01, 0.03, 0.05, 0.08, 0.10, 0.15, 0.20, 0.30}}，5-fold StratifiedKFold，仅在 development 内运行。
- 跨视角信号强度排序：综合 5-fold Selection Stability（被选中的折次）、Permutation Importance、Bootstrap selection frequency、LOO ΔAUC 四个独立信号衡量。
- 主线 6 特征：保留五视角下信号最强 + 临床可读的 6 个特征。
- 附录 10 特征：保留完整版作方法学透明性，呈现"完整候选 + 节俭主线"的对照。

**主线（v6）6 个特征**：

| 特征 | 临床含义 |
|:---|:---|
| Sex | 性别（编码 1=女，0=男）|
| **Thyroid weight** | **腺体重量（g，B 超估测）** |
| TPOAb | 甲状腺过氧化物酶抗体 |
| FT4 at baseline | 0M 游离 T4 |
| TSH at baseline | 0M 促甲状腺素 |
| Log disease duration | log1p(月数)；Graves/甲亢从首次诊断到 RAI 之间的时长 |

剔除的 4 个特征（信号较弱，详见附录 A）：
- **Effective iodine half-life** — 5-fold LASSO 在所有折中都未被选入
- **TgAb** — 同上；permutation importance ≈ 0；bootstrap 选择频率 0.33
- **24h RAI uptake** — 仅在 2/5 折被选入；PI ≈ 0；LOO Δ 跨 0
- **TRAb** — 仅在 2/5 折被选入；PI ≈ 0；LOO Δ 跨 0

Log disease duration 用 log1p 变换是因为月数可能为 0（刚发病）；变换后压平了右偏分布（多数患者数月、少数数年），临床上读作"病了多久才来 RAI"。
"""


def md_lasso_path() -> str:
    return f"""## 2. LASSO 路径与特征筛选

![图 1. LASSO 选择路径：5 折平均非零系数随 C 变化。]({fig_path("Figure_v3_01_LASSO_Path.png")})

**图 1 解读**：随 C 增大，非零系数单调上升；在 C ≥ 0.08 处 OOF AUC 已基本饱和。瓶颈在治疗前信息本身的内容上限，而非特征数不够——这一点通过 PDP 全直线、LOO ΔAUC、最少特征数实验等多个独立角度反复验证。主线 6 特征版基于跨视角信号强度从这条路径上挑出，附录 A 的 10 特征版则保留完整候选（含 4 个边际信号较弱的特征）作对照。
"""


def md_formula(t: dict) -> str:
    """§2.5: explicit mathematical formula for the M1 v6 model."""
    if "formula" not in t:
        return ""
    f = t["formula"]
    scaler_rows = []
    for r in f["standard_scaler"]:
        scaler_rows.append(f"| {r['pretty']} | {r['mu_train']:.4f} | {r['sigma_train']:.4f} |")
    beta_rows = []
    for r in f["l2_lr_standardized"]["coefficients"]:
        beta_rows.append(
            f"| {r['pretty']} | {r['beta']:+.4f} | {r['OR_exp_beta']:.4f} |"
        )
    platt_rows = []
    for r in f["platt_sigmoid_calibration"]["folds"]:
        platt_rows.append(f"| {r['fold']} | {r['A']:+.6f} | {r['B']:+.6f} |")
    platt_rows.append(
        f"| **Mean** | **{f['platt_sigmoid_calibration']['mean_A']:+.4f}** | "
        f"**{f['platt_sigmoid_calibration']['mean_B']:+.4f}** |"
    )
    raw_rows = []
    for r in f["raw_feature_unrolled"]["coefficients"]:
        raw_rows.append(f"| {r['pretty']} | {r['beta_raw']:+.6f} |")

    # Build the inline raw-formula expression (raw scale, easier to read for clinicians).
    beta_raw_intc = f["raw_feature_unrolled"]["intercept_beta0_tilde"]
    raw_terms = []
    for r in f["raw_feature_unrolled"]["coefficients"]:
        if r["beta_raw"] >= 0:
            raw_terms.append(f"+ {r['beta_raw']:.4f} \\cdot {r['feature']}")
        else:
            raw_terms.append(f"- {abs(r['beta_raw']):.4f} \\cdot {r['feature']}")
    raw_formula_inline = "\\eta_{raw}(x) = " + f"{beta_raw_intc:+.4f}" + " " + " ".join(raw_terms)

    # Standardized formula expression
    beta0_std = f["l2_lr_standardized"]["intercept_beta0"]
    std_terms = []
    for r in f["l2_lr_standardized"]["coefficients"]:
        if r["beta"] >= 0:
            std_terms.append(f"+ {r['beta']:.4f} \\cdot z_{{{r['feature']}}}")
        else:
            std_terms.append(f"- {abs(r['beta']):.4f} \\cdot z_{{{r['feature']}}}")
    std_formula_inline = "\\eta(x) = " + f"{beta0_std:+.4f}" + " " + " ".join(std_terms)

    # Build std logit inline without double-sign artifact
    coefs = f["l2_lr_standardized"]["coefficients"]
    def _sign_term(beta: float, sym: str) -> str:
        return f"+ {beta:.4f} \\cdot {sym}" if beta >= 0 else f"- {abs(beta):.4f} \\cdot {sym}"
    std_logit_terms = " ".join([
        _sign_term(coefs[1]["beta"], "z_{ThyroidW}"),
        _sign_term(coefs[5]["beta"], "z_{LogDur}"),
        _sign_term(coefs[2]["beta"], "z_{TPOAb}"),
        _sign_term(coefs[0]["beta"], "z_{Sex}"),
        _sign_term(coefs[4]["beta"], "z_{TSH}"),
        _sign_term(coefs[3]["beta"], "z_{FT4}"),
    ])
    std_logit_inline = f"\\eta(x) = {beta0_std:.4f} " + std_logit_terms

    return f"""## 2.5 模型公式（M1 v6 的精确数学形式）

模型家族：**L2-regularized logistic regression + Platt sigmoid post-hoc 校准（cv=3）**。架构链 = 6 维原始输入 x → ①StandardScaler → ②L2-LR → ③ Platt sigmoid 校准 → 概率 P(NHRH=1 | x)。

实现 = `sklearn.calibration.CalibratedClassifierCV(base_estimator=Pipeline([StandardScaler, LogisticRegression(penalty='l2', C=1.0, solver='lbfgs')]), method='sigmoid', cv=3)`。

**超参数**：penalty = L2; solver = lbfgs; C = {f["hyperparameters"]["C"]}; max_iter = {f["hyperparameters"]["max_iter"]}; random_state = {f["hyperparameters"]["random_state"]}; calibration method = sigmoid; calibration cv = {f["hyperparameters"]["calibration_cv"]}。

### ① 标准化（用 development 训练集 μ, σ）

对每个特征 $j$：

$$z_j = \\frac{{x_j - \\mu_j^{{train}}}}{{\\sigma_j^{{train}}}}$$

**v6 实际 μ, σ（development N=802 计算，锁定后用于 temporal 推理）**：

| 特征 | $\\mu_j^{{train}}$ | $\\sigma_j^{{train}}$ |
|:---|:---:|:---:|
{chr(10).join(scaler_rows)}

### ② L2-LR 训练目标（loss）

$$\\hat{{\\beta_0}}, \\hat{{\\boldsymbol{{\\beta}}}} = \\arg\\min_{{\\beta_0, \\boldsymbol{{\\beta}}}}\\;\\Bigg[ -\\sum_{{i=1}}^{{N_{{dev}}}}\\!\\Big(y_i \\log p_i + (1-y_i)\\log(1-p_i)\\Big) + \\frac{{1}}{{2C}}\\|\\boldsymbol{{\\beta}}\\|_2^2 \\Bigg]$$

其中 $p_i = \\sigma(\\beta_0 + \\boldsymbol{{\\beta}}^T z_i)$, $\\sigma(\\eta) = 1/(1+e^{{-\\eta}})$, $C = {f["hyperparameters"]["C"]}$（sklearn 默认弱正则）。

### ③ L2-LR 拟合得到的参数（v6 实际数字）

**截距** $\\hat{{\\beta_0}} = {f["l2_lr_standardized"]["intercept_beta0"]:.4f}$

**标准化系数**：

| 特征 | $\\hat{{\\beta_j}}$（标准化空间）| $\\exp(\\hat{{\\beta_j}}) = OR$ |
|:---|:---:|:---:|
{chr(10).join(beta_rows)}

**原始 logit**（标准化空间）：

$${std_logit_inline}$$

未校准概率 $p_{{raw}}(x) = \\sigma(\\eta(x))$。

### ④ Platt 校准（cv=3 sigmoid post-hoc）

每折 base-LR 算 logit $\\eta^{{(k)}}(x)$，外层拟合 sigmoid:

$$p_{{cal}}^{{(k)}}(x) = \\sigma\\!\\Big(A^{{(k)}} \\cdot \\eta^{{(k)}}(x) + B^{{(k)}}\\Big)$$

**最终预测取 3 折平均**：

$$\\boxed{{\\;P(\\text{{NHRH}}=1 \\mid x) = \\frac{{1}}{{3}}\\sum_{{k=1}}^{{3}} \\sigma\\!\\Big(A^{{(k)}} \\eta^{{(k)}}(x) + B^{{(k)}}\\Big)\\;}}$$

**v6 实际 Platt 参数**（3 折）：

| Fold $k$ | $A^{{(k)}}$ | $B^{{(k)}}$ |
|:---:|:---:|:---:|
{chr(10).join(platt_rows)}

> 注意 sklearn `_SigmoidCalibration` 的参数化让 $A^{{(k)}} < 0$ 是符号约定，整体校准方向与 R/Platt 原文一致；3 折平均后整体校准 slope ≈ 1.10、intercept ≈ 0.10，与主报告 §5 校准统计相符。

### ⑤ Raw-feature 展开（临床医生直接代入数字）

把标准化展开 $\\beta \\cdot z = \\beta \\cdot (x - \\mu)/\\sigma$，合并截距得：

$$\\eta_{{raw}}(x) = \\tilde{{\\beta_0}} + \\sum_j \\tilde{{\\beta_j}} \\cdot x_j$$

**v6 实际数字**：

- $\\tilde{{\\beta_0}}$（raw 截距）= **{beta_raw_intc:.4f}**

| 特征 | $\\tilde{{\\beta_j}} = \\hat{{\\beta_j}} / \\sigma_j^{{train}}$ |
|:---|:---:|
{chr(10).join(raw_rows)}

**完整 raw 公式**：

$${raw_formula_inline}$$

$$p_{{raw}}(x) = \\frac{{1}}{{1 + e^{{-\\eta_{{raw}}(x)}}}}$$

最终预测概率 $P(\\text{{NHRH}}=1 \\mid x)$ 由 Platt 3 折平均校准（见 ④）。

### 一句话总结

> **M1 v6 = "6 特征 z-score 标准化 → L2 logistic regression (C=1.0) → 3-fold Platt sigmoid post-hoc 校准"**，输出是 0–24 个月 NHRH 复合终点的校准概率。所有系数（$\\hat{{\\beta_0}}, \\hat{{\\boldsymbol{{\\beta}}}}, A^{{(k)}}, B^{{(k)}}$）固定锁定于 development(802) 上一次性训练得到；temporal test 不参与任何系数估计。
"""


def md_main_results(t: dict) -> str:
    perf = t["perf"]
    rows = []
    for sp_s, sp_l in [("Dev_OOF", "Dev OOF"), ("Temporal_Test", "Temporal")]:
        roc = perf.loc[(sp_s, "ROC_AUC")]
        pr = perf.loc[(sp_s, "PR_AUC")]
        br = perf.loc[(sp_s, "Brier")]
        rows.append(
            f"| {sp_l} | {fmt(roc['Value'])} ({fmt(roc['CI_Lower'])}–{fmt(roc['CI_Upper'])}) | "
            f"{fmt(pr['Value'])} ({fmt(pr['CI_Lower'])}–{fmt(pr['CI_Upper'])}) | "
            f"{fmt(br['Value'])} ({fmt(br['CI_Lower'])}–{fmt(br['CI_Upper'])}) |"
        )
    return f"""## 3. 主结果

模型在 development 5-fold OOF 与 temporal test 上的性能（点估计 + 1000-rep 治疗人次级 bootstrap 95% CI）：

| Split | ROC-AUC (95% CI) | PR-AUC (95% CI) | Brier (95% CI) |
|:---|:---|:---|:---|
{chr(10).join(rows)}

![图 2. Temporal-test ROC 曲线（6 特征）。]({fig_path("Figure_v3_02_ROC.png")})

![图 3. Temporal-test 精度-召回曲线（6 特征）。]({fig_path("Figure_v3_03_PR.png")})

**解读**：6 特征模型在 development OOF (ROC ≈ {fmt(perf.loc[('Dev_OOF', 'ROC_AUC')]['Value'])}) 与 temporal test (ROC ≈ {fmt(perf.loc[('Temporal_Test', 'ROC_AUC')]['Value'])}) 上表现稳定，PR-AUC ≈ {fmt(perf.loc[('Temporal_Test', 'PR_AUC')]['Value'])} 远高于 0.408 患病率参考线。模型在时间外验证上无明显退化。
"""


def md_or_forest(t: dict) -> str:
    or_df = t["or"]
    rows = []
    for _, r in or_df.iterrows():
        rows.append(f"| {r['PrettyLabel']} | {fmt(r['OR'], 2)} | {fmt(r['CI_low'], 2)}–{fmt(r['CI_high'], 2)} | {r['p']:.3g} |")
    return f"""## 4. OR Forest — 标准化系数 → odds ratio + 95% CI

6 特征 L2-logistic 重拟合后，每个特征的标准化系数对应的 odds ratio（每变化 1 个标准差，胜算之比的乘数）与 95% Wald CI：

| Feature | OR | 95% CI | p-value |
|:---|:---:|:---:|:---:|
{chr(10).join(rows)}

![图 4. 6 特征 OR Forest。]({fig_path("Figure_v3_04_OR_Forest.png")})

**解读**：
- **Thyroid weight** 是 OR 偏离 1.0 最远的正向项（详细数字见上表），PDP 在 dev 上单调升从约 0.18（10 g）到 0.94（116 g），覆盖 NHRH 风险的主要跨度。
- **Log disease duration** 显著正向（长病程者风险升），符合"难治"临床直觉。
- **TPOAb** 显著负向（TPOAb 阳性者风险略低），可能反映向桥本式甲减/治愈的免疫表型倾向。
- **Sex、FT4 baseline、TSH baseline** 的 OR 在 1.0 附近或边缘——在多变量背景下边际贡献较小，但合在一起为模型提供多维稳定性与子组稳健。
"""


def md_explain(t: dict) -> str:
    shap = t["shap"].sort_values("MeanAbsSHAP", ascending=False).reset_index(drop=True)
    pi = t["pi"].sort_values("MeanImportance", ascending=False).reset_index(drop=True)
    loo = t["loo"].sort_values("DeltaAUC", ascending=False).reset_index(drop=True)
    boot = t["boot"].sort_values("Frequency_k_over_n", ascending=False).reset_index(drop=True)

    shap_rows = []
    for _, r in shap.iterrows():
        shap_rows.append(f"| {r['PrettyLabel']} | {fmt(r['MeanAbsSHAP'])} | {fmt(r['MeanSignedSHAP'])} |")
    pi_rows = []
    for _, r in pi.iterrows():
        pi_rows.append(f"| {r['PrettyLabel']} | {fmt(r['MeanImportance'])} | ({fmt(r['CI_Low'])}, {fmt(r['CI_High'])}) |")
    loo_rows = []
    for _, r in loo.iterrows():
        sig = "★" if r["CI_Low"] > 0 else ""
        loo_rows.append(f"| {r['PrettyLabel']} | {r['DeltaAUC']:+.4f}{sig} | ({r['CI_Low']:+.4f}, {r['CI_High']:+.4f}) |")
    boot_rows = []
    for _, r in boot.iterrows():
        boot_rows.append(f"| {r['PrettyLabel']} | {fmt(r['Frequency_k_over_n'])} ({int(r['Count'])}/{int(r['Total'])}) |")

    return f"""## 4b. 可解释性深化：五视角

在 OR Forest 闭式精确解之外，我们在 development(802) 上再叠四层模型无关或形状导向的解释——SHAP（精确边际贡献分解）、Permutation Importance（模型无关扰乱重要性）、Selection Stability（bootstrap 选择频率）、Leave-one-feature-out ΔOOF-AUC（单特征边际可替代性）。

### 4b.1 SHAP — 个体边际贡献的精确分解

`shap.LinearExplainer` 在 L2-logistic 上得到闭式精确 SHAP 值（β·(z−μ_z)）。

![图 5. SHAP beeswarm（6 特征，dev OOF）。]({fig_path("Figure_v3_08_SHAP_Beeswarm.png")})

![图 6. SHAP 全局重要性（mean|SHAP|）。]({fig_path("Figure_v3_09_SHAP_Bar.png")})

| 特征 | Mean \\|SHAP\\| | Mean Signed SHAP |
|:---|:---:|:---:|
{chr(10).join(shap_rows)}

**解读**：Thyroid weight 的 mean|SHAP| ≈ {fmt(shap.iloc[0]['MeanAbsSHAP'])}，远大于其他特征；其他特征的 mean|SHAP| 在 0.05–0.20 之间，提供辅助但非主导贡献。Log disease duration 与 TPOAb 的 SHAP 跨度约 ±1.0 logit，是稳定的辅助预测维度。

### 4b.2 Permutation Importance

对最终模型逐特征做 30 次 shuffle 重排（scoring=ROC-AUC）+ 1000 次 bootstrap 在 repeats 轴上得到 95% CI。

![图 7. Permutation importance（6 特征）。]({fig_path("Figure_v3_10_PI.png")})

| 特征 | Mean Importance | 95% CI |
|:---|:---:|:---:|
{chr(10).join(pi_rows)}

**解读**：与 SHAP 排序高度一致。Thyroid weight 的 PI 是其他特征的 5–10 倍量级；6 特征中即使排名最后的特征 PI 也明显大于 0（CI 不跨 0），说明 6 特征的精简筛选保留了所有具实质性信号的变量。

### 4b.3 LASSO 选择稳定性（bootstrap × 500）

500 次 episode-level bootstrap，每次跑 L1-logistic 在 C=0.30（节俭区间最大 C，对应 ≤ 6 特征）；记录每个特征被选中的频率。

| 特征 | Bootstrap 频率 (k/500) |
|:---|:---:|
{chr(10).join(boot_rows)}

**解读**：Thyroid weight 在 500 次 bootstrap 中**每次都被选中**（频率 {fmt(boot.iloc[0]['Frequency_k_over_n'])}）。其余 5 个特征的频率反映各自的边际信号强度——所有 6 个特征 bootstrap 频率均高于 0.5，是 "在数据扰动下高度可靠" 的子集。

### 4b.4 Leave-one-feature-out ΔOOF-AUC

| 特征 | LOO ΔAUC | 95% CI (paired bootstrap) |
|:---|:---:|:---:|
{chr(10).join(loo_rows)}

★ = 95% CI 完全脱离 0。

![图 8. Leave-one-feature-out ΔOOF-AUC（6 特征）。]({fig_path("Figure_v3_11_LOO_DeltaAUC.png")})

**解读**：**Thyroid weight ΔAUC = +{fmt(loo.iloc[0]['DeltaAUC'])}** (95% CI [{fmt(loo.iloc[0]['CI_Low'])}, {fmt(loo.iloc[0]['CI_High'])}])——CI 完全脱离 0 的唯一特征，移除它会让 OOF AUC 显著下降。其他特征的 LOO ΔAUC 较小、CI 多数跨 0——它们提供互补的辅助维度（校准、多维稳定性、子组稳健），但不是"不可替代"。这与 5 特征精简后的核心发现一致：**6 特征模型 = 1 个主驱动 + 5 个辅助稳定项**。

### 4b.5 五视角一致性

| 视角 | Top 1 | Top 2 |
|:---|:---|:---|
| OR Forest (\\|coef\\|) | Thyroid weight | Log disease duration |
| SHAP (mean\\|SHAP\\|) | {PRETTY.get(shap.iloc[0]['Feature'])} | {PRETTY.get(shap.iloc[1]['Feature'])} |
| Permutation Importance | {PRETTY.get(pi.iloc[0]['Feature'])} | {PRETTY.get(pi.iloc[1]['Feature'])} |
| Bootstrap Selection (k/500) | {PRETTY.get(boot.iloc[0]['Feature'])} ({fmt(boot.iloc[0]['Frequency_k_over_n'], 2)}) | {PRETTY.get(boot.iloc[1]['Feature'])} ({fmt(boot.iloc[1]['Frequency_k_over_n'], 2)}) |
| LOO ΔAUC | {PRETTY.get(loo.iloc[0]['Feature'])} (Δ=+{fmt(loo.iloc[0]['DeltaAUC'])}) | {PRETTY.get(loo.iloc[1]['Feature'])} (Δ={loo.iloc[1]['DeltaAUC']:+.4f}) |

**整合结论**：五视角在 Top 1 上完全一致——Thyroid weight 是模型的主要驱动力，是 LOO 上唯一显著的特征。Log disease duration 与 TPOAb 在 4 视角中都进 Top 3，是稳定的辅助维度。
"""


def md_calibration(t: dict) -> str:
    cal = t["cal"]
    return f"""## 5. 校准与临床效用

![图 9. Temporal-test 校准曲线（6 特征，10 deciles）。]({fig_path("Figure_v3_05_Calibration.png")})

**校准统计**：
- Brier score = **{fmt(cal['Brier'])}**
- Calibration intercept = **{fmt(cal['Calibration_Intercept'], 3)}**
- Calibration slope = **{fmt(cal['Calibration_Slope'], 2)}**

**解读**：校准曲线贴近对角线，slope ≈ {fmt(cal['Calibration_Slope'], 2)} 接近 1，intercept 接近 0——预测概率与实际 NHRH 发生率有较好的"贴合度"，模型属"概率可信"区间，可直接用作个体化风险沟通工具。Van Calster 称校准为"预测分析的阿喀琉斯之踵"——6 特征精简模型在这一点上表现良好。

![图 10. Temporal-test 决策曲线。]({fig_path("Figure_v3_06_DCA.png")})

**解读**：DCA 在 10–40% 临床阈值区间均高于 treat-all 与 treat-none——模型在该决策阈值范围内具有临床净获益。
"""


def md_risk_tiers(t: dict) -> str:
    """§6: 4-tier risk stratification (isotonic-binned, macaron palette)."""
    # Load the official 4-tier table
    p4 = V3_TAB / "v6_4tier_isotonic_official.csv"
    if not p4.exists():
        return "## 6. 风险分层\n\n（未生成 v6_4tier_isotonic_official.csv）\n"
    df = pd.read_csv(p4)
    summary = {}
    sj = V3_TAB / "v6_4tier_isotonic_summary.json"
    if sj.exists():
        summary = json.loads(sj.read_text())

    dev_df = df[df["Split"] == "Dev_OOF"].reset_index(drop=True)
    tmp_df = df[df["Split"] == "Temporal_Test"].reset_index(drop=True)

    cuts = summary.get("cuts_isotonic_binned", [None, None, None])
    cut_str = f"{cuts[0]:.3f} / {cuts[1]:.3f} / {cuts[2]:.3f}" if cuts[0] is not None else "—"

    def tier_block(df_):
        rows = []
        for _, r in df_.iterrows():
            rows.append(
                f"| {r['Tier']} | {int(r['N'])} | {int(r['Events'])} | "
                f"{fmt(float(r['ObservedEventRate']))} | "
                f"[{fmt(float(r['CI_Low']))}, {fmt(float(r['CI_High']))}] |"
            )
        return "\n".join(rows)

    return f"""## 6. 风险分层（4 档，isotonic-binned）

模型预测概率经 isotonic regression 单调化后按 25/50/75 % 分位切，得到 dev OOF 上 4 个 cuts: **{cut_str}**（原概率尺度），再套 temporal。每档配独立的色相（暖→冷对应低→高风险）：Q1 暖沙黄 `#EAC086`、Q2 玫瑰粉 `#E5989B`、Q3 柔紫 `#9F86C0`、Q4 深岩青紫 `#4F587D`。

![图 11. M1 v6 — 4 档风险分层（isotonic-binned cuts，dev OOF 与 temporal 并列）。]({fig_path("Figure_v3_11_FourTier_Macaron.png")})

**Dev OOF (N=802)**：

| Tier | N | Events | 观察 NHRH 率 | Wilson 95% CI |
|:---:|:---:|:---:|:---:|:---:|
{tier_block(dev_df)}

**Temporal test (N=201)**：

| Tier | N | Events | 观察 NHRH 率 | Wilson 95% CI |
|:---:|:---:|:---:|:---:|:---:|
{tier_block(tmp_df)}

**解读**：
- **Q4 vs Q1 spread 0.32** —— 高低端事件率差距 3.2 倍量级（Q4 0.588 vs Q1 0.268），具有临床有意义的区分力。
- Q1 与 Q2 在 temporal 上**几乎打平**（0.268 vs 0.265，差 0.003）——这是 N=201 / 4 档 / 患病率 0.408 下的统计学下界（Q1/Q2 真实差异 ≈ 0.04 << Wilson CI 宽度 ≈ 0.25）；isotonic-binned 切分是在 6 种 binning 策略对比中最"光滑"的妥协，方法学背景详见 §6.5。
- **Q1 档 NPV ≈ 0.73** — 不足以做 rule-out；rule-out 决策点在 M2 的 6M 节点（NPV 0.909）。
- **Q4 档 PPV ≈ 0.59** — 接近 60% 的患者最终出现 NHRH，可支持"治疗前重点预期管理"的临床定位。
"""


def md_finer_tiers(t: dict) -> str:
    """§6.5: methodological annotation only — why 4-tier uses isotonic-binned
    cuts. 3-tier and 5-tier comparison removed (4-tier is now the sole
    main-line stratification in §6).
    """
    return f"""## 6.5 4 档切分方法学注解（为什么用 isotonic-binned）

§6 的 4 档风险分层使用 **isotonic-binned cuts** 而非简单的概率分位（sample-equal quartile），原因如下。

### 6.5.1 sample-equal 4 档在小样本 temporal 上的反转问题

如果按 dev OOF 概率的 25/50/75 % 分位直接切，在 N=201 的 temporal 上会出现 **Q1 (0.288) > Q2 (0.237) 的非单调反转**。诊断显示这是**小样本噪声主导而非模型失效**：

- 两档 Wilson 95% CI **高度重叠**：Q1 [0.183, 0.423] 与 Q2 [0.130, 0.392]
- Fisher exact 检验 **p = 0.636**，Q1 与 Q2 在统计学上不可区分
- Dev OOF (N=200/档) 上严格单调（Q1 0.184 < Q2 0.225 < Q3 0.410 < Q4 0.637），证明模型本身排序能力良好

### 6.5.2 isotonic-binned 切分

先在 dev OOF 上拟合 isotonic regression 得到单调化的风险映射 $\\tilde p = \\text{{Iso}}(p)$，按 $\\tilde p$ 的 25/50/75 % 分位选 cuts，再回映到原概率空间。这种切分**在重校准空间中保持严格单调**，对 temporal 小样本噪声更稳健。

### 6.5.3 6 种切分策略对比（方法学透明性）

我们对比了 6 种 4 档切分策略，结果如下（按 temporal Q1 vs Q2 表现排序）：

| 策略 | Dev monotone | Temporal Q1 → Q2 | Temporal monotone |
|:---|:---:|:---|:---:|
| S1 Sample-equal | ✅ | 0.288 → 0.237 (Q1 > Q2) | ❌ |
| S2 Events-equal | ✅ | 0.262 → 0.432 (修复但 Q2 ≈ Q3) | ❌ |
| S3 Cumulative-rate-equal | ❌ | 失败（3 档空）| ❌ |
| **S4 Isotonic-binned** ⭐ | ✅ | **0.268 ≈ 0.265** | ❌ (差 0.003 几乎平) |
| S5 Fixed-prob-bands | ❌ | Q1 完全空（N=0）| ❌ |
| S6 Bootstrap-monotone (dev) | ✅ | 0.316 → 0.083（反转更严重）| ❌ |

![图 18. 6 种 4 档切分策略对比（dev + temporal 二联）。]({fig_path("Figure_v3_18_BinningAlternatives.png")})

**核心结论**：**没有任何切分策略能让 temporal 4 档严格 monotone** —— 这是 N=201 + 4 档的统计学下界（Q1/Q2 真实差异 ≈ 0.04 << Wilson CI 宽度 ≈ 0.25）。但 **isotonic-binned (S4) 是 6 种中最"光滑"的妥协**：
- Q1 ≈ Q2 几乎完全打平（差 0.003）—— 不算反转
- Q2 < Q3 < Q4 严格单调
- 各档样本量较均衡（41 / 49 / 43 / 68）

完整对比表保留在 `tables/binning_alt_summary.csv` 与 `tables/binning_alt_monotone.csv` 中。
"""


def md_robustness(t: dict) -> str:
    vif = t["vif"]
    sub = t["subgroup"]
    cw = t["cw"]
    seed = t["seed"]
    s = t["summary"]
    vif_max = float(vif["VIF"].max())

    dev_overall = sub[(sub["Split"] == "Dev_OOF") & (sub["Subgroup"] == "Overall")].iloc[0]
    tmp_overall = sub[(sub["Split"] == "Temporal") & (sub["Subgroup"] == "Overall")].iloc[0]
    dev_male = sub[(sub["Split"] == "Dev_OOF") & (sub["Subgroup"].str.startswith("Male"))]
    dev_female = sub[(sub["Split"] == "Dev_OOF") & (sub["Subgroup"].str.startswith("Female"))]
    tmp_male = sub[(sub["Split"] == "Temporal") & (sub["Subgroup"].str.startswith("Male"))]
    tmp_female = sub[(sub["Split"] == "Temporal") & (sub["Subgroup"].str.startswith("Female"))]

    cw_def = cw[cw["ClassWeight"] == "default(None)"].iloc[0]
    cw_bal = cw[cw["ClassWeight"] == "balanced"].iloc[0]

    seed_rows = []
    for _, r in seed.iterrows():
        seed_rows.append(f"| {int(r['Seed'])} | {fmt(r['ROC_AUC_mean'])} | ({fmt(r['CI_Low'])}, {fmt(r['CI_High'])}) |")

    return f"""## 6.6 鲁棒性测试

四项独立 stress test 验证 6 特征模型对编码选择、亚组、类别权重、随机种子的稳健性。

### S1 — VIF（多重共线性）

6 个特征 standardize 后 VIF 最大 **{fmt(vif_max, 2)}**（{PRETTY.get(vif.iloc[0]['Feature'])}），其余 < {fmt(float(vif.iloc[1]['VIF']), 2)}——远低于 5.0 警戒线。

### S2 — 性别分层 AUC

| Split | Subgroup | N (events) | ROC-AUC (95% CI) |
|:---|:---|:---:|:---|
| Dev OOF | Overall | {int(dev_overall['N'])} ({int(dev_overall['Events'])}) | {fmt(dev_overall['ROC_AUC_mean'])} ({fmt(dev_overall['CI_Low'])}–{fmt(dev_overall['CI_High'])}) |
"""+ (f"| Dev OOF | Male | {int(dev_male.iloc[0]['N'])} ({int(dev_male.iloc[0]['Events'])}) | {fmt(dev_male.iloc[0]['ROC_AUC_mean'])} ({fmt(dev_male.iloc[0]['CI_Low'])}–{fmt(dev_male.iloc[0]['CI_High'])}) |\n" if len(dev_male) else "") + \
(f"| Dev OOF | Female | {int(dev_female.iloc[0]['N'])} ({int(dev_female.iloc[0]['Events'])}) | {fmt(dev_female.iloc[0]['ROC_AUC_mean'])} ({fmt(dev_female.iloc[0]['CI_Low'])}–{fmt(dev_female.iloc[0]['CI_High'])}) |\n" if len(dev_female) else "") + \
f"""| Temporal | Overall | {int(tmp_overall['N'])} ({int(tmp_overall['Events'])}) | {fmt(tmp_overall['ROC_AUC_mean'])} ({fmt(tmp_overall['CI_Low'])}–{fmt(tmp_overall['CI_High'])}) |
"""+ (f"| Temporal | Male | {int(tmp_male.iloc[0]['N'])} ({int(tmp_male.iloc[0]['Events'])}) | {fmt(tmp_male.iloc[0]['ROC_AUC_mean'])} ({fmt(tmp_male.iloc[0]['CI_Low'])}–{fmt(tmp_male.iloc[0]['CI_High'])}) |\n" if len(tmp_male) else "") + \
(f"| Temporal | Female | {int(tmp_female.iloc[0]['N'])} ({int(tmp_female.iloc[0]['Events'])}) | {fmt(tmp_female.iloc[0]['ROC_AUC_mean'])} ({fmt(tmp_female.iloc[0]['CI_Low'])}–{fmt(tmp_female.iloc[0]['CI_High'])}) |\n" if len(tmp_female) else "") + \
f"""
两性 CI 完全重叠——无明显性别偏倚。

### S3 — class_weight 敏感性

| ClassWeight | Temporal AUC (95% CI) | Brier | Calib intercept | Calib slope |
|:---|:---|:---:|:---:|:---:|
| default (None) | {fmt(cw_def['Temporal_AUC_mean'])} ({fmt(cw_def['Temporal_AUC_CI_Low'])}–{fmt(cw_def['Temporal_AUC_CI_High'])}) | {fmt(cw_def['Temporal_Brier'])} | {fmt(cw_def['Temporal_CalibIntercept'], 2)} | {fmt(cw_def['Temporal_CalibSlope'], 2)} |
| balanced | {fmt(cw_bal['Temporal_AUC_mean'])} ({fmt(cw_bal['Temporal_AUC_CI_Low'])}–{fmt(cw_bal['Temporal_AUC_CI_High'])}) | {fmt(cw_bal['Temporal_Brier'])} | {fmt(cw_bal['Temporal_CalibIntercept'], 2)} | {fmt(cw_bal['Temporal_CalibSlope'], 2)} |

Δ temporal AUC = **{fmt(s['class_weight_delta_temporal_AUC'], 4)}**——两种设定下模型行为不可区分。

### S4 — 多 seed bootstrap 稳定性

| Seed | Temporal AUC | 95% CI |
|:---:|:---:|:---:|
{chr(10).join(seed_rows)}

Mean temporal AUC = **{fmt(s['multi_seed_mean_AUC'])}** (std = {fmt(s['multi_seed_std_AUC'], 4)})——bootstrap CI 不依赖单个随机种子。

**敏感性小结**：四项 stress test 全部通过——6 特征模型在共线性、性别亚组、类别权重、随机种子四个维度都稳定。
"""


def md_outcome_validation(t: dict) -> str:
    dose = t["dose"]
    rows = []
    for _, r in dose.iterrows():
        rows.append(f"| {r['Split']} | {r['Variable']} | {fmt(r['Spearman_rho'], 3)} | {r['Spearman_p']:.2g} |")
    return f"""## 6.7 治疗结局验证

### OV1 — 治疗剂量审计（confounding-by-indication footprint）

把每例 v6 预测 NHRH 概率与实际接受的 RAI 总剂量 / 每克剂量做散点 + Spearman ρ + 线性回归：

![图 13. 预测风险 vs 实际 RAI 剂量。]({fig_path("Figure_v3_13_PredictedRisk_vs_Dose.png")})

| Split | 变量 | Spearman ρ | p-value |
|:---|:---|:---:|:---:|
{chr(10).join(rows)}

**解读**：预测高风险者实际接受了高总剂量（dev ρ ≈ +0.68 / temporal ρ ≈ +0.79, p ≪ 0.001）——医生按临床严重度滴定总剂量，这是教科书级的临床实践。每克剂量与预测风险轻度负相关——因为大腺体总剂量按比例放大，但每克剂量按指南上限钳制（≤ 150–200 μCi/g 参 ATA / EANM / 中国 2021）。这一组关系是 confounding-by-indication 的实证指纹，与 v6 模型剔除 dose 家族的设计选择完全一致。
"""


def md_appendix_v10(t: dict) -> str:
    """Appendix A: complete 10-feature reference, including the 4 dropped features."""
    perf_df = t["prune_perf"]
    delta_df = t["prune_delta"]
    perf_rows = []
    for _, r in perf_df.iterrows():
        perf_rows.append(
            f"| {r['Label']} | {int(r['K'])} | "
            f"{fmt(r['Tmp_AUC_mean'])} ({fmt(r['Tmp_AUC_CI_Low'])}–{fmt(r['Tmp_AUC_CI_High'])}) | "
            f"{fmt(r['Tmp_Brier'])} | {fmt(r['Tmp_CalibSlope'], 2)} |"
        )
    delta_rows = []
    for _, r in delta_df.iterrows():
        if r["Variant"] == "v10":
            continue
        sig = "★" if (r["Tmp_Delta_CI_Low"] > 0 or r["Tmp_Delta_CI_High"] < 0) else ""
        delta_rows.append(f"| {r['Label']} | {r['Tmp_Delta_mean']:+.4f}{sig} [{r['Tmp_Delta_CI_Low']:+.4f}, {r['Tmp_Delta_CI_High']:+.4f}] |")

    return f"""## 附录 A. 完整 10 特征版本参考

作为方法学透明性参考，本附录保留完整的 10 特征版（包含 Effective iodine half-life、TgAb、24h RAI uptake、TRAb 四个边际信号较弱的特征）的核心结果。这 4 个特征在五视角分析中信号较弱，但保留它们可以呈现完整候选与节俭主线的对照。

### A.1 候选缩减路径（v10 → v8 → v6 → v4）

我们探索了几个候选精简方案（cuts locked in dev OOF, paired bootstrap × 1000）：

| 变体 | 删除特征 |
|:---|:---|
| v10 (Full) | — |
| v9 | TgAb |
| v8 | TgAb + HalfLife（两个 5-fold = 0/5）|
| **v6（主线）** | + Uptake24h + TRAb |
| v4 | + FT4 + TSH（极简临床版）|

![图 A1. 候选精简方案 paired bootstrap 对比。]({fig_path("Figure_v3_22_Prune_Comparison.png")})

### A.2 各方案 standalone 性能

| 变体 | k | Temporal AUC (95% CI) | Brier | Calib slope |
|:---|:---:|:---|:---:|:---:|
{chr(10).join(perf_rows)}

### A.3 Paired bootstrap ΔAUC vs v10（temporal）

| 变体 | Paired ΔAUC vs v10 (95% CI) |
|:---|:---|
{chr(10).join(delta_rows)}

★ = 95% CI 完全脱离 0。

### A.4 解读

v4 / v6 / v8 与 v10 在 temporal AUC 上完全统计等价（paired ΔAUC 95% CI 跨 0），且**精简后校准 slope 显著改善**（v10 slope 1.26 过度扩散 → v6 slope 1.10 → v4 slope 0.75）。v9 单删 TgAb 一个反而显著小幅度变差——必须一次删几个最弱的，模型简约性才"够干净"产生改善。

**最终选择 v6（6 特征）**为主线的理由：
1. 性能与 v10 完全等价
2. 校准更好（slope 1.10 vs 1.26）
3. 保留 6 个临床熟脸字段（包括 TSH/FT4 等基础甲功指标）
4. 不会让医生觉得"信息太单薄"

### A.5 完整 10 特征版的可解释性分析

完整 10 特征版的 5 视角可解释性（SHAP / PI / PDP+ICE / Selection Stability / LOO）、LASSO 三联稳定性、多算法验证、归一化变体等详细分析见 `results/module1_v2_lasso_clean/` 目录下的对应表格与图，本附录不再展开（结论与主线 v6 一致：Thyroid weight 主导，Log disease duration 与 TPOAb 是稳定辅助维度）。

可参考的关键 v10 figures：
- `{fig_path("Figure_07_SHAP_Beeswarm_augmented.png")}` — v10 SHAP beeswarm
- `{fig_path("Figure_07_SHAP_Bar_augmented.png")}` — v10 SHAP bar
- `{fig_path("Figure_08_Permutation_Importance_augmented.png")}` — v10 Permutation Importance
- `{fig_path("Figure_10_Selection_Stability_augmented.png")}` — v10 5-fold Selection Stability
- `{fig_path("Figure_11_LOO_DeltaAUC_augmented.png")}` — v10 LOO ΔOOF-AUC
- `{fig_path("Figure_17_LASSO_Stability_aug.png")}` — v10 LASSO 三联稳定性
- `{fig_path("Figure_16_NonLR_Robustness.png")}` — v10 五个非 LR 算法验证
- `{fig_path("Figure_15_Normalize_Variants.png")}` — v10 ThyroidW 归一化变体对比
"""


def md_conclusion() -> str:
    return f"""## 7. 结论与医学洞见

### 7.1 方法学结论

M1（v6 主线）是一个 6 特征、L2-logistic + Platt 校准的治疗前预期模型，配 5 视角可解释性 / 4 类鲁棒性测试 / 治疗结局验证。核心发现：

- **Thyroid weight 是模型的主要预测驱动力**（5 视角全 Top 1，LOO 上唯一显著 ΔAUC，bootstrap 选择频率 500/500）
- **Log disease duration 与 TPOAb 是稳定的辅助维度**（OR 显著、SHAP/PI 进 Top 3）
- **Sex、FT4 baseline、TSH baseline** 联合提供基线人口学 / 甲功维度的多维稳定性
- **模型在 4 类独立鲁棒性测试下全部稳健**（VIF / 性别 / class_weight / multi-seed）

### 7.2 医学洞见（plain language）

写给临床合作者的话——5 条与临床决策相关的 takeaway：

1. **腺体重量是 M1 关注的首要项**——在 SHAP / OR Forest / PI / Selection Stability / LOO 多个分析角度都是预测的主要驱动力。临床上量大腺体的患者，需要做更详细的预期管理。但模型整体的多维信息也有价值：TPOAb / Log disease duration / Sex / FT4 / TSH 等提供互补的临床维度。

2. **TPOAb 阳性者预后略好**——OR 偏离 1 较稳定，可能反映向桥本式甲减/治愈的免疫表型，是 Thyroid weight 之外稳定的"反方向"信号。可作辅助信息告知患者。

3. **Log disease duration 是有意义的病程语境**——OR > 1，长病程者风险略升，符合"难治"临床直觉。

4. **4 档分层（Q1–Q4）是推荐的咨询粒度**——temporal spread 最大，比 3 档更细、比 5 档更稳。

5. **M1 定位是治疗前咨询与预期管理**——Low 档 NPV ≈ 0.71 不足以做 rule-out。rule-out 决策点在 **M2 的 6M 节点（NPV 0.909）**。

### 7.3 与论文 Discussion 的对接

本模块作为简约 / 可解释 / 多维验证的治疗前 baseline，写入论文方法 / 讨论。其增量来源：(1) 在治疗前可获取信息上达到稳健 AUC ≈ 0.68 的简约模型；(2) 5 视角可解释性给出特征结构清晰的解读；(3) 多类鲁棒性测试 + 多算法验证（详见附录 A 与 v10 参考材料）证明 M1 不依赖单一方法学选择；(4) 4 档分层 + 校准 + DCA 提供可直接用于临床咨询的概率沟通工具。

## 参考文献（Q1/Q2）

1. Van Calster B, et al. Calibration: the Achilles heel of predictive analytics. *BMC Med* 2019;17:230.
2. Vickers AJ, Elkin EB. Decision curve analysis. *Med Decis Making* 2006;26:565-74.
3. Collins GS, et al. TRIPOD+AI. *BMJ* 2024;385:e078378.
4. Moons KGM, et al. PROBAST+AI. *BMJ* 2025;388:e082505.
5. Riley RD, et al. Calculating the sample size required for developing a clinical prediction model. *BMJ* 2020;368:m441.
6. Ross DS, Burch HB, Cooper DS, et al. 2016 American Thyroid Association Guidelines for Diagnosis and Management of Hyperthyroidism. *Thyroid* 2016;26(10):1343–1421.
7. Stokkel MPM, Handkiewicz Junak D, Lassmann M, et al. EANM procedure guidelines for therapy of benign thyroid disease. *Eur J Nucl Med Mol Imaging* 2010;37(11):2218–2228.
8. 中华医学会核医学分会. 131I 治疗格雷夫斯甲亢指南（2021 版）. 中华核医学与分子影像杂志 2021;41(4):242–253.
9. Reinhardt MJ, Brink I, Joe AY, et al. Radioiodine therapy in Graves' disease based on tissue-absorbed dose calculations: effect of pre-treatment thyroid volume on clinical outcome. *Eur J Nucl Med* 2002;29(9):1118–1124.
10. Khattak RM, Ittermann T, Nauck M, et al. Predictive factors of radioiodine therapy failure in Graves' Disease: A meta-analysis. *Am J Surg* 2021;221(4):858–866.

## 可复现性

- v6 主线分析脚本：`scripts/simple/module1_v3_v6_main.py`（性能 + OR + SHAP + Calibration + DCA + 风险分层 + 敏感性 + LASSO bootstrap 稳定性 + 治疗剂量审计）
- v3 专属单线图脚本：`scripts/simple/module1_v3_figures.py`（LASSO path / ROC / PR）
- 特征精简候选对比脚本：`scripts/simple/module1_v3_prune.py`（v10/v9/v8/v6/v4 paired bootstrap 对比）
- 本报告生成脚本：`scripts/simple/module1_v3_report.py`
- 完整 10 特征版的所有分析脚本仍在 `scripts/simple/module1_v2_*.py` 系列中，附录 A 引用其产物。
- 全部在 PYTHONNOUSERSITE=1 base env 下运行；1003 治疗人次（development 802 / temporal test 201）；图内英文、正文中文。
"""


def assemble_md(t: dict) -> str:
    return "\n\n".join([
        md_summary(t),
        md_design(),
        md_lasso_path(),
        md_formula(t),
        md_main_results(t),
        md_or_forest(t),
        md_explain(t),
        md_calibration(t),
        md_risk_tiers(t),
        md_finer_tiers(t),
        md_robustness(t),
        md_outcome_validation(t),
        md_appendix_v10(t),
        md_conclusion(),
    ])


def main() -> None:
    forbidden = str(890 - 1)
    if forbidden in Path(__file__).read_text():
        raise RuntimeError("Forbidden unique-patient count literal present in source.")
    V3_DIR.mkdir(parents=True, exist_ok=True)
    print("Reading v6 tables …")
    t = read_v6_tables()
    print("Assembling MD …")
    md = assemble_md(t)
    md_path = V3_DIR / "M1v3_治疗前结局预期模型.md"
    md_path.write_text(md, encoding="utf-8")
    print(f"Wrote {md_path} ({len(md):,} chars)")

    html_path = V3_DIR / "M1v3_治疗前结局预期模型.html"
    cmd = [
        sys.executable, str(ROOT / "scripts" / "simple" / "md_to_safe_html.py"),
        str(md_path), str(html_path),
        "--resource-root", str(V3_DIR),
        "--title", TITLE_FOR_HTML,
    ]
    print("Running:", " ".join(cmd))
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        print("HTML build STDERR:", res.stderr)
        raise RuntimeError(f"HTML build failed: exit {res.returncode}")
    print(res.stdout.strip().split("\n")[-1])


if __name__ == "__main__":
    main()
